# Generated by Django 5.0.6 on 2024-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_api', '0003_alter_knowledgebasefile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='path',
            field=models.FileField(upload_to='knowledgebases'),
        ),
    ]
