# Generated by Django 5.0.6 on 2024-05-25 21:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_api', '0004_alter_knowledgebasefile_path'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmed'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='knowledgebasefile',
            name='knowledgebase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='network_api.knowledgebase'),
        ),
        migrations.CreateModel(
            name='AccountActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Activation Code')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
